### ISSUE TITLE
"Cannot install package luci-app-passwall" because of "check_data_file_clashes ... * dnsmasq" 

### ISSUE THREAD

**Issue by jkk-oh** [dianlujitao/openwrt-passwall-build#2]
Download worked fine through mirror, package installing & configuring too, but I get an error due to Data_file_clashes (last lines of screen output):
`check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-passwall.`

(Netgear 6250, OpenWrt 21.02.0 r16279-5cc0535800 / LuCI openwrt-21.02 branch git-21.231.26241-422c175)

Full screen output during installation:
`root@OpenWrt:/# opkg install luci-app-passwall
Installing luci-app-passwall (4.36) to root...
Downloading http://ftp.halifax.rwth-aachen.de/osdn/storage/g/o/op/openwrt-passwall-build/releases/21.02.0/packages/arm_cortex-a9/passwall/luci-app-passwall_4.36_all.ipk
Installing coreutils (8.32-6) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/packages/coreutils_8.32-6_arm_cortex-a9.ipk
Installing coreutils-base64 (8.32-6) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/packages/coreutils-base64_8.32-6_arm_cortex-a9.ipk
Installing coreutils-nohup (8.32-6) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/packages/coreutils-nohup_8.32-6_arm_cortex-a9.ipk
Installing libnghttp2-14 (1.43.0-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/packages/libnghttp2-14_1.43.0-1_arm_cortex-a9.ipk
Installing libcurl4 (7.78.0-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/packages/libcurl4_7.78.0-1_arm_cortex-a9.ipk
Installing curl (7.78.0-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/packages/curl_7.78.0-1_arm_cortex-a9.ipk
Installing libgmp10 (6.2.1-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/base/libgmp10_6.2.1-1_arm_cortex-a9.ipk
Installing libnettle8 (3.6-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/base/libnettle8_3.6-1_arm_cortex-a9.ipk
Installing kmod-nfnetlink (5.4.143-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/targets/bcm53xx/generic/packages/kmod-nfnetlink_5.4.143-1_arm_cortex-a9.ipk
Installing kmod-ipt-ipset (5.4.143-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/targets/bcm53xx/generic/packages/kmod-ipt-ipset_5.4.143-1_arm_cortex-a9.ipk
Installing libnfnetlink0 (1.0.1-4) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/base/libnfnetlink0_1.0.1-4_arm_cortex-a9.ipk
Installing kmod-nf-conntrack-netlink (5.4.143-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/targets/bcm53xx/generic/packages/kmod-nf-conntrack-netlink_5.4.143-1_arm_cortex-a9.ipk
Installing libmnl0 (1.0.4-2) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/base/libmnl0_1.0.4-2_arm_cortex-a9.ipk
Installing libnetfilter-conntrack3 (1.0.8-1) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/base/libnetfilter-conntrack3_1.0.8-1_arm_cortex-a9.ipk
Installing dnsmasq-full (2.85-8) to root...
Downloading https://downloads.openwrt.org/releases/21.02.0/packages/arm_cortex-a9/base/dnsmasq-full_2.85-8_arm_cortex-a9.ipk
Configuring kmod-nfnetlink.
Configuring coreutils.
Configuring coreutils-base64.
Configuring libnfnetlink0.
Configuring kmod-nf-conntrack-netlink.
Configuring libmnl0.
Configuring libnetfilter-conntrack3.
Configuring libnghttp2-14.
Configuring libcurl4.
Configuring curl.
Configuring libgmp10.
Configuring libnettle8.
Configuring kmod-ipt-ipset.
Configuring coreutils-nohup.
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/acl.d/dnsmasq_acl.json
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-passwall.
`

**Comment by dianlujitao** [comment]
```sh
opkg remove dnsmasq
opkg install dnsmasq-full
```
