### ISSUE TITLE
lua & uci not found

### ISSUE THREAD

**Issue by jkk-oh** [dianlujitao/openwrt-passwall-build#3]
Install & config without errors, lua & uci not found in the end (& openwrt no longer starting with WebUI):
`Configuring luci-app-passwall.
lua: /usr/lib/lua/luci/model/cbi/passwall/api/api.lua:6: module 'luci.cbi.datatypes' not found:
	no field package.preload['luci.cbi.datatypes']
	no file './luci/cbi/datatypes.lua'
	no file '/usr/share/lua/luci/cbi/datatypes.lua'
	no file '/usr/share/lua/luci/cbi/datatypes/init.lua'
	no file '/usr/lib/lua/luci/cbi/datatypes.lua'
	no file '/usr/lib/lua/luci/cbi/datatypes/init.lua'
	no file './luci/cbi/datatypes.so'
	no file '/usr/lib/lua/luci/cbi/datatypes.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/cbi/passwall/api/api.lua:6: in main chunk
	[C]: in function 'require'
	...r/lib/lua/luci/model/cbi/passwall/server/api/app.lua:4: in main chunk
	[C]: ?
uci: Entry not found`

**Comment by dianlujitao** [comment]
```sh
opkg install luci-compat
```
